//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Mail Template</summary>
	[PublishedContentModel("MailTemplate")]
	public partial class MailTemplate : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "MailTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MailTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MailTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Bcc emails: Use semicolon separator as delimiter.
		///</summary>
		[ImplementPropertyType("bccEmails")]
		public string BccEmails
		{
			get { return this.GetPropertyValue<string>("bccEmails"); }
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("body")]
		public IHtmlString Body
		{
			get { return this.GetPropertyValue<IHtmlString>("body"); }
		}

		///<summary>
		/// CC emails: Use semicolon separator as delimiter.
		///</summary>
		[ImplementPropertyType("ccEmails")]
		public string CcEmails
		{
			get { return this.GetPropertyValue<string>("ccEmails"); }
		}

		///<summary>
		/// Email type
		///</summary>
		[ImplementPropertyType("emailType")]
		public object EmailType
		{
			get { return this.GetPropertyValue("emailType"); }
		}

		///<summary>
		/// Extra tokens
		///</summary>
		[ImplementPropertyType("extraTokens")]
		public string ExtraTokens
		{
			get { return this.GetPropertyValue<string>("extraTokens"); }
		}

		///<summary>
		/// From email
		///</summary>
		[ImplementPropertyType("fromEmail")]
		public string FromEmail
		{
			get { return this.GetPropertyValue<string>("fromEmail"); }
		}

		///<summary>
		/// From name
		///</summary>
		[ImplementPropertyType("fromName")]
		public string FromName
		{
			get { return this.GetPropertyValue<string>("fromName"); }
		}

		///<summary>
		/// Subject
		///</summary>
		[ImplementPropertyType("subject")]
		public string Subject
		{
			get { return this.GetPropertyValue<string>("subject"); }
		}

		///<summary>
		/// To
		///</summary>
		[ImplementPropertyType("to")]
		public Archetype.Models.ArchetypeModel To
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("to"); }
		}
	}
}
