//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>System Link</summary>
	[PublishedContentModel("systemLink")]
	public partial class SystemLink : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "systemLink";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SystemLink(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SystemLink, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Links
		///</summary>
		[ImplementPropertyType("links")]
		public Newtonsoft.Json.Linq.JToken Links
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("links"); }
		}

		///<summary>
		/// Links Group Title
		///</summary>
		[ImplementPropertyType("linksGroupTitle")]
		public string LinksGroupTitle
		{
			get { return this.GetPropertyValue<string>("linksGroupTitle"); }
		}

		///<summary>
		/// Sort
		///</summary>
		[ImplementPropertyType("sort")]
		public int Sort
		{
			get { return this.GetPropertyValue<int>("sort"); }
		}
	}
}
