export const emojiList = [
  {
    src: "../../../../../../../assets/emoji/angry.svg",
    title: "Smile (:))",
    shortcut: ":)",
    width: "20",
    height: "20",
    class: "emoji-icon smile",
  },
  {
    src: "../../../../../../../assets/emoji/sad.svg",
    title: "Sad (:()",
    shortcut: ":(",
    width: "20",
    height: "20",
    class: "emoji-icon sad",
  },
  {
    src: "../../../../../../../assets/emoji/wink.svg",
    title: "Wink (;))",
    shortcut: ";)",
    width: "20",
    height: "20",
    class: "emoji-icon wink",
  },
  {
    src: "../../../../../../../assets/emoji/shocked.svg",
    title: "Shocked (:|)",
    shortcut: ":|",
    width: "20",
    height: "20",
    class: "emoji-icon shocked",
  },
  {
    src: "../../../../../../../assets/emoji/tease.svg",
    title: "Tease (:p)",
    shortcut: ":p",
    width: "20",
    height: "20",
    class: "emoji-icon tease",
  },
  {
    src: "../../../../../../../assets/emoji/funny.svg",
    title: "Funny (:D)",
    shortcut: ":D",
    width: "20",
    height: "20",
    class: "emoji-icon funny",
  },
  {
    src: "../../../../../../../assets/emoji/angry.svg",
    title: "Angry (:<)",
    shortcut: ":<",
    width: "20",
    height: "20",
    class: "emoji-icon angry",
  },
  {
    src: "../../../../../../../assets/emoji/skeptical.svg",
    title: "Skeptical (:^))",
    shortcut: ":^",
    width: "20",
    height: "20",
    class: "emoji-icon skeptical",
  },
  {
    src: "../../../../../../../assets/emoji/surprised.svg",
    title: "Surprised (:o)",
    shortcut: ":o",
    width: "20",
    height: "20",
    class: "emoji-icon surprised",
  },
  {
    src: "../../../../../../../assets/emoji/great.svg",
    title: "Great (:+1)",
    shortcut: ":+1",
    width: "20",
    height: "20",
    class: "emoji-icon great",
  },
  {
    src: "../../../../../../../assets/emoji/joy.svg",
    title: "Joy (:-))",
    shortcut: ":-)",
    width: "20",
    height: "20",
    class: "emoji-icon joy",
  },
  {
    src: "../../../../../../../assets/emoji/love.svg",
    title: "Love (:x)",
    shortcut: ":x",
    width: "20",
    height: "20",
    class: "emoji-icon love",
  },
  {
    src: "../../../../../../../assets/emoji/party.svg",
    title: "Party (<o))",
    shortcut: "<o",
    width: "20",
    height: "20",
    class: "emoji-icon party",
  },
  {
    src: "../../../../../../../assets/emoji/fever.svg",
    title: "Fever (fever)",
    shortcut: "fever",
    width: "20",
    height: "20",
    class: "emoji-icon fever",
  },
  {
    src: "../../../../../../../assets/emoji/sleepy.svg",
    title: "Sleepy (|-))",
    shortcut: "|-)",
    width: "20",
    height: "20",
    class: "emoji-icon sleepy",
  },
]
