const emojiPath = '../../../../../../../assets/emoji/';

export const emojiList = [
  {
    src: emojiPath + "smile.svg",
    title: "Smile (:))",
    shortcut: ":)",
    width: "20",
    height: "20",
    class: "emoji-icon smile",
  },
  {
    src: emojiPath + "sad.svg",
    title: "Sad (:()",
    shortcut: ":(",
    width: "20",
    height: "20",
    class: "emoji-icon sad",
  },
  {
    src: emojiPath + "wink.svg",
    title: "Wink (;))",
    shortcut: ";)",
    width: "20",
    height: "20",
    class: "emoji-icon wink",
  },
  {
    src: emojiPath + "shocked.svg",
    title: "Shocked (:|)",
    shortcut: ":|",
    width: "20",
    height: "20",
    class: "emoji-icon shocked",
  },
  {
    src: emojiPath + "tease.svg",
    title: "Tease (:p)",
    shortcut: ":p",
    width: "20",
    height: "20",
    class: "emoji-icon tease",
  },
  {
    src: emojiPath + "funny.svg",
    title: "Funny (:D)",
    shortcut: ":D",
    width: "20",
    height: "20",
    class: "emoji-icon funny",
  },
  {
    src: emojiPath + "angry.svg",
    title: "Angry (:<)",
    shortcut: ":<",
    width: "20",
    height: "20",
    class: "emoji-icon angry",
  },
  {
    src: emojiPath + "skeptical.svg",
    title: "Skeptical (:^))",
    shortcut: ":^",
    width: "20",
    height: "20",
    class: "emoji-icon skeptical",
  },
  {
    src: emojiPath + "surprised.svg",
    title: "Surprised (:o)",
    shortcut: ":o",
    width: "20",
    height: "20",
    class: "emoji-icon surprised",
  },
  {
    src: emojiPath + "great.svg",
    title: "Great (:+1)",
    shortcut: ":+1",
    width: "20",
    height: "20",
    class: "emoji-icon great",
  },
  {
    src: emojiPath + "joy.svg",
    title: "Joy (:-))",
    shortcut: ":-)",
    width: "20",
    height: "20",
    class: "emoji-icon joy",
  },
  {
    src: emojiPath + "love.svg",
    title: "Love (:x)",
    shortcut: ":x",
    width: "20",
    height: "20",
    class: "emoji-icon love",
  },
  {
    src: emojiPath + "party.svg",
    title: "Party (<o))",
    shortcut: "<o",
    width: "20",
    height: "20",
    class: "emoji-icon party",
  },
  {
    src: emojiPath + "fever.svg",
    title: "Fever (:fever)",
    shortcut: ":fever",
    width: "20",
    height: "20",
    class: "emoji-icon fever",
  },
  {
    src: emojiPath + "sleepy.svg",
    title: "Sleepy (|-))",
    shortcut: "|-)",
    width: "20",
    height: "20",
    class: "emoji-icon sleepy",
  },
]
