import {
  Component,
  OnInit,
  Input,
  Output,
  EventEmitter,
  ViewEncapsulation,
  HostListener
} from "@angular/core";
import { IPinedData } from "../pin-activity/pin-activity.component";
import { ISelectItem } from "../../../reusable/inputs/select/select.component";
import { IDatepickerData } from "../datepicker-from-to/datepiker-from-to.interface";
import { ITagData } from "../../../reusable/inputs/tag-multiselect/tag-multiselect.interface";
import { INewsCreateModel, IOwner } from "../activity.interfaces";
import { ILocationResult } from "../../../reusable/ui-elements/location-picker/location-picker.interface";
import { NewsFormService } from "./news-form.service";
import { PinActivityService } from '../pin-activity/pin-activity.service';
import { HasDataChangedService } from 'src/app/shared/services/general/has-data-changed.service';
import { TranslateService } from '@ngx-translate/core';
import * as moment from "moment";

@Component({
  selector: "app-news-form",
  templateUrl: "./news-form.component.html",
  styleUrls: ["./news-form.component.less"],
  encapsulation: ViewEncapsulation.None
})
export class NewsFormComponent implements OnInit {
  @Input() data: INewsCreateModel;
  @Input() members: Array<any>;
  @Input() creator: IOwner;
  @Input() tags: ITagData[];
  @Input() pinAllowed: boolean;
  @Input() isSubmitLoading: boolean;
  @Input('edit') edit: any;

  @Output() handleSubmit = new EventEmitter();
  @Output() handleCancel = new EventEmitter();
  @HostListener('window:beforeunload') checkIfDataChanged() {
    return !this.hasDataChangedService.hasDataChanged;
  }

  isShowValidation: boolean;
  newsData: INewsCreateModel;
  selectedTags: ITagData[] = [];
  isAccepted: boolean;
  owners: ISelectItem[];
  defaultOwner: ISelectItem;
  initialDates: {
    from: string;
    to: string;
  };
  initialLocation: string;
  // File it's array where file[0] is file's object generated by dropzone and file[1] is id
  files: Array<any> = [];
  routerSubscription: any;

  constructor(
    private newsFormService: NewsFormService,
    private pinActivityService: PinActivityService,
    private hasDataChangedService: HasDataChangedService,
    public translate: TranslateService,
    ) {}

  ngOnInit() {
    this.edit = this.edit !== undefined;
    this.newsData = this.newsFormService.getNewsDataInitialValue(this.data);
    this.setInitialData();
  }

  private setInitialData(): void {
    this.owners = this.newsFormService.getMembers(this.members);

    this.defaultOwner = this.creator
      ? this.owners.find(x => x.id === this.creator.id)
      : null;

    this.selectedTags = this.data.tags || [];

    this.initialDates = {
      from: this.data.publishDate || undefined,
      to: this.data.unpublishDate || undefined
    };

    this.initialLocation =
      (this.data.location && this.data.location.address) || null;

    if (this.newsData.isPinned) {
      this.isAccepted = true;
    }
  }

  get isInvalidEndPinDate() {
    return (
      this.newsData.isPinned &&
      (this.newsData.endPinDate < this.newsData.publishDate ||
        this.newsData.endPinDate > this.newsData.unpublishDate)
    );
  }

  // File functions
  onUploadSuccess(fileArray: Array<any> = []): void {
    this.files.push(fileArray);
    this.hasDataChangedService.onDataChanged();
  }
  onFileRemoved(removedFile: object) {
    this.files = this.files.filter(file => file[0] !== removedFile);
    this.hasDataChangedService.onDataChanged();
  }
  public handleImageRemove(image): void {
    this.newsData.media.medias = this.newsData.media.medias.filter(
      m => m !== image
    );
    this.hasDataChangedService.onDataChanged();
  }
  public handleFileRemove(file): void {
    this.newsData.media.otherFiles = this.newsData.media.otherFiles.filter(
      m => m !== file
    );
    this.hasDataChangedService.onDataChanged();
  }

  // Data set functions
  setDatePickerValue(value: IDatepickerData = {}) {
    const test = moment(this.initialDates.from).format();
    if ((!this.initialDates.to && value.to)
      || (moment(this.initialDates.from).format() != value.from && moment(this.initialDates.from).subtract(5, "seconds").format() != value.from)
      || (this.initialDates.to && moment(this.initialDates.to).format() != value.to && moment(this.initialDates.to).add(5, "seconds").format() != value.to)) {
      this.hasDataChangedService.onDataChanged();
    }
    this.pinActivityService.setPublishDates(value);
    this.newsData.publishDate = value.from;
    this.newsData.unpublishDate = value.to;
  }
  setPinValue(value: IPinedData) {
    if (this.data.endPinDate !== this.newsData.endPinDate) {
      this.hasDataChangedService.onDataChanged();
    }
    this.newsData.endPinDate = value.pinDate;
    this.newsData.isPinned = value.isPinCheked;
    this.isAccepted = value.isAccepted;
  }
  setLocationValue(location: ILocationResult): void {
    this.newsData.location.address = location.address;
    this.newsData.location.shortAddress = location.shortAddress;
    this.hasDataChangedService.onDataChanged();
  }

  // Main submit function
  onSubmit() {
    this.isShowValidation = true;

    if (this.validate()) {
      this.newsDataBuilder();
      this.handleSubmit.emit(this.newsData);
    }
  }

  //Main cancel function
  onCancel() {
    this.handleCancel.emit();
  }

  private validate(): boolean {
    const pinValid = this.newsData.isPinned ? this.isAccepted : true;
    const title = this.newsData.title.trim();

    return (
      title && this.getStripDescription() && pinValid
      // !this.isInvalidEndPinDate
    );
  }

  getStripDescription() {
    return this.newsData.description.replace(/&nbsp;/g, " ").replace(/<[^>]*>?/gm, "").trim();
  }

  private newsDataBuilder(): void {
    this.newsData.newMedia = this.newsFormService.getMediaIdsForResponse(this.files);
    this.newsData.tagIdsData = this.newsFormService.getTagsForResponse(this.selectedTags);
  }

  changeOwner(owner: ISelectItem | string) {
    if (typeof owner === "string") {
      this.newsData.ownerId = owner;
    } else {
      this.newsData.ownerId = owner.id;
    }
    if (this.defaultOwner.id !== this.newsData.ownerId) {
      this.hasDataChangedService.onDataChanged();
    }
  }

  onTitleChange(e) {
    if (this.newsData.title != e) {
      this.hasDataChangedService.onDataChanged();
    }
    this.newsData.title = e;
  }

  onDescriptionChange(e) {
    if (this.newsData.description != e) {
      this.hasDataChangedService.onDataChanged();
    }
    this.newsData.description = e;
  }
}
