// <auto-generated />
namespace Compent.Uintra.Persistence.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LinkPreviewEntity_AddMediaIdForLocalRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkPreviewEntity_AddMediaIdForLocalRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201910101139332_LinkPreviewEntity_AddMediaIdForLocalRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
