// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Uintra20.Persistence.Sql.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBulletins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBulletins));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111252106_AddBulletins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
