// <auto-generated />
namespace Compent.uIntra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename));
        
        string IMigrationMetadata.Id
        {
            get { return "201706230716541_Rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
